name = input("Enter your name: ")
q1, q2, q3 = input("Enter your Marks: ").split()
total = int(q1) + int(q2) + int(q3)
print(f"Your name is {name}!")
print(f"Your Total is: {total}")
print(f"Your Avg is: {total / 3:.2f}")